"""user table change migration

Revision ID: 8d3cdfedb88f
Revises: d35806d604d0
Create Date: 2023-07-30 09:22:24.781470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3cdfedb88f'
down_revision = 'd35806d604d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
