"""add model comment migration

Revision ID: bc790e123e20
Revises: ed02f31e67ce
Create Date: 2023-07-30 02:26:00.066920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc790e123e20'
down_revision = 'ed02f31e67ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
