"""add total comment in announcement table comment migration

Revision ID: d35806d604d0
Revises: bc790e123e20
Create Date: 2023-07-30 09:04:36.163944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35806d604d0'
down_revision = 'bc790e123e20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('total_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'total_comments')
    # ### end Alembic commands ###
