"""announcement change  migration

Revision ID: ed02f31e67ce
Revises: 8dc8ffe6005f
Create Date: 2023-07-29 20:04:10.742667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed02f31e67ce'
down_revision = '8dc8ffe6005f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False))
    # ### end Alembic commands ###
